### ISSUE TITLE
DOC: Suggested logo

### ISSUE THREAD

**Issue by HaoZeke** [amritagos/solvis#1]
![DALL·E 2023-11-30 15 49 23 - Design a sophisticated logo for 'Solvis', a Python-centric computational chemistry project  The logo should combine a polyhedral shape, representing t](https://github.com/amritagos/solvis/assets/4336207/31987e49-dd5b-4020-8d39-00a5817420cb)

I would recommend a `branding/logo` folder at the project root :)

Generated via DALL-E through ChatGPT4.

**Comment by amritagos** [comment]
Thank you so much for this beautiful logo! :) I would love to
